### ISSUE TITLE
0.2.0版本webpack-hmr插件运行antd-init的模板异常

### ISSUE THREAD

**Issue by cooclsee** [dora-js/dora-plugin-webpack-hmr#3]
dora使用0.4.3版本，dora-plugin-webpack-hmr使用0.2.0版本。

执行命令

```
dora --plugins \"proxy,webpack,webpack-hmr,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html\"
```

没有出现`xxx/xxx build modules`提示，并且访问`http://localhost:8989`，出现如下异常提示：

```
err with request :Error: connect ECONNREFUSED 127.0.0.1:8000
```

**Comment by soda-x** [comment]
dora-plugin-webpack-hmr 升级到 0.2.1 看看

**Comment by cooclsee** [comment]
正常了

**Comment by YunaiV** [comment]
@cooclsee 你好，我目前也碰到类似的问题，请问是如何解决的。
@pigcan 我的dora-plugin-webpack-hmr是0.2.1版本，辛苦帮忙看看：https://github.com/dora-js/dora-plugin-webpack-hmr/issues/5
