### ISSUE TITLE
webpack-hmr启动后范根报错

### ISSUE THREAD

**Issue by YunaiV** [dora-js/dora-plugin-webpack-hmr#5]
配置webpack-hmr后，启动访问时，命令行报错：err with request :Error: connect ECONNREFUSED 127.0.0.1:8000  /

package.json配置如下：
"dora": "0.4.3",
"dora-plugin-livereload": "0.5.3",
"dora-plugin-proxy": "0.8.4",
"dora-plugin-browser-history": "0.2.0",
"dora-plugin-webpack": "0.8.1",
"dora-plugin-webpack-hmr": "0.2.1"

启动命令如下："start": "dora --plugins \"webpack-hmr,proxy,webpack,browser-history?index=/src/index.html,livereload?enableJs=false&injectHost=127.0.0.1\""

谢谢。

**Comment by cooclsee** [comment]
是不是8000端口被占用了

**Comment by YunaiV** [comment]
@cooclsee 谢谢解答。
8000端口未被占用。
请问你现在webpack-hmr是怎么配置的？

**Comment by YunaiV** [comment]
已解决。配置的时候，webpack-hmr放在webpack后面。启动脚本如下：

"start": "dora --plugins \"proxy,webpack,webpack-hmr,browser-history?index=/src/index.html,livereload?enableJs=false&injectHost=127.0.0.1\"",
